NAV_STATUS_MAP = {
    "0": "Under way using engine",
    "1": "At anchor",
    "2": "Not under command",
    "3": "Restricted maneuverability",
    "4": "Constrained by her draught",
    "5": "Moored",
    "6": "Aground",
    "7": "Engaged in Fishing",
    "8": "Under way sailing",
    "9": "Reserved for future amendment (HSC)",
    "10": "Reserved for future amendment (WIG)",
    "11": "Reserved for future use",
    "12": "Reserved for future use",
    "13": "Reserved for future use",
    "14": "AIS-SART",
    "15": "Undefined",
}

VESSEL_TYPES = {
    "0": "Not available",
    "20": "Wing in ground",
    "21": "Wing in ground (WIG) - Hazardous category A",
    "22": "Wing in ground (WIG) - Hazardous category B",
    "23": "Wing in ground (WIG) - Hazardous category C",
    "24": "Wing in ground (WIG) - Hazardous category D",
    "25": "Wing in ground (WIG) - Reserved for future use",
    "26": "Wing in ground (WIG) - Reserved for future use",
    "27": "Wing in ground (WIG) - Reserved for future use",
    "28": "Wing in ground (WIG) - Reserved for future use",
    "29": "Wing in ground (WIG) - Reserved for future use",
    "30": "Fishing",
    "31": "Towing",
    "32": "Towing - length exceeds 200m",
    "33": "Dredging or underwater ops",
    "34": "Diving ops",
    "35": "Military ops",
    "36": "Sailing",
    "37": "Pleasure craft",
    "38": "Reserved for future use",
    "39": "Reserved for future use",
    "40": "HSC",
    "41": "HSC - Hazardous category A",
    "42": "HSC - Hazardous category B",
    "43": "HSC - Hazardous category C",
    "44": "HSC - Hazardous category D",
    "45": "HSC - Reserved for future use",
    "46": "HSC - Reserved for future use",
    "47": "HSC - Reserved for future use",
    "48": "HSC - Reserved for future use",
    "49": "HSC - Reserved for future use",
    "50": "Pilot vessel",
    "51": "Search and Rescue vessel",
    "52": "Tug",
    "53": "Port Tender",
    "54": "Anti-piracy",
    "55": "Law enforcement",
    "56": "Reserved for future use",
    "57": "Reserved for future use",
    "58": "Reserved for future use",
    "59": "Reserved for future use",
    "60": "Passenger",
    "61": "Passenger - Hazardous category A",
    "62": "Passenger - Hazardous category B",
    "63": "Passenger - Hazardous category C",
    "64": "Passenger - Hazardous category D",
    "65": "Passenger - Reserved for future use",
    "66": "Passenger - Reserved for future use",
    "67": "Passenger - Reserved for future use",
    "68": "Passenger - Reserved for future use",
    "69": "Passenger - Reserved for future use",
    "70": "Cargo",
    "71": "Cargo - Hazardous category A",
    "72": "Cargo - Hazardous category B",
    "73": "Cargo - Hazardous category C",
    "74": "Cargo - Hazardous category D",
    "75": "Cargo - Reserved for future use",
    "76": "Cargo - Reserved for future use",
    "77": "Cargo - Reserved for future use",
    "78": "Cargo - Reserved for future use",
    "79": "Cargo - Reserved for future use",
    "80": "Tanker",
    "81": "Tanker - Hazardous category A",
    "82": "Tanker - Hazardous category B",
    "83": "Tanker - Hazardous category C",
    "84": "Tanker - Hazardous category D",
    "85": "Tanker - Reserved for future use",
    "86": "Tanker - Reserved for future use",
    "87": "Tanker - Reserved for future use",
    "88": "Tanker - Reserved for future use",
    "89": "Tanker - Reserved for future use",
    "90": "Other",
    "91": "Other - Hazardous category A",
    "92": "Other - Hazardous category B",
    "93": "Other - Hazardous category C",
    "94": "Other - Hazardous category D",
    "95": "Other - Reserved for future use",
    "96": "Other - Reserved for future use",
    "97": "Other - Reserved for future use",
    "98": "Other - Reserved for future use",
    "99": "Other - Reserved for future use",
}

AIS_MESSAGE_PREFIXES = ("!AIVDM", "!AIVDO", "$AIVDM", "$AIVDO")

DEFAULT_BASE_URL = "https://www.aggsoft.com/cgi-perl/ais/decode_ais.pl"
DEFAULT_TIMEOUT = 30.0
DEFAULT_BATCH_DELAY = 1.0